name: CI - Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      
      - name: Purge
        run: apt-get purge needrestart
        
      - name : Test Build
        uses: QiubyZ/kivy-build@v1
        with:
          buildozer_cmd: |
            buildozer -v android clean |
            echo 'yes' | buildozer -v android debug


      - name: Buat Rilis Baru
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1
          name: Clock #Test Release
          files: ${{ github.workspace }}/bin/*.apk  
          draft: false
          prerelease: false
          generate_release_notes: false 
