name: CI - Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name : Test Build
        uses: QiubyZ/kivy-build@v1
        with:
          buildozer_cmd: |
            expect -c '
            spawn buildozer -v android debug
            expect "Some prompt requiring yes"
            send "y\r"
            interact'
        
