name: CI - Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Test Build
        uses: QiubyZ/kivy-build@v1
        with:
          buildozer_cmd: |
            yes | buildozer -v android debug
